// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrt6Si0i5Em5oc2YznDbLa9E4H1-kQ1xk',
    appId: '1:63696119677:web:5840bdeb9e4f1a6d1a8e14',
    messagingSenderId: '63696119677',
    projectId: 'my-finances-a3878',
    authDomain: 'my-finances-a3878.firebaseapp.com',
    storageBucket: 'my-finances-a3878.firebasestorage.app',
    measurementId: 'G-HPH9R7KHY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq8Oyx53I4IptXyJbCpTH_rKYry1ud4Tk',
    appId: '1:63696119677:android:ba4e3c8997d4baa41a8e14',
    messagingSenderId: '63696119677',
    projectId: 'my-finances-a3878',
    storageBucket: 'my-finances-a3878.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKlAM696RM8nXWPlExywUaytM1wd7y6HI',
    appId: '1:63696119677:ios:e9e85cdef0a8c9b71a8e14',
    messagingSenderId: '63696119677',
    projectId: 'my-finances-a3878',
    storageBucket: 'my-finances-a3878.firebasestorage.app',
    iosBundleId: 'com.example.myFinances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKlAM696RM8nXWPlExywUaytM1wd7y6HI',
    appId: '1:63696119677:ios:e9e85cdef0a8c9b71a8e14',
    messagingSenderId: '63696119677',
    projectId: 'my-finances-a3878',
    storageBucket: 'my-finances-a3878.firebasestorage.app',
    iosBundleId: 'com.example.myFinances',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrt6Si0i5Em5oc2YznDbLa9E4H1-kQ1xk',
    appId: '1:63696119677:web:5edf3cec3a0853ab1a8e14',
    messagingSenderId: '63696119677',
    projectId: 'my-finances-a3878',
    authDomain: 'my-finances-a3878.firebaseapp.com',
    storageBucket: 'my-finances-a3878.firebasestorage.app',
    measurementId: 'G-CXL1HRQVB1',
  );
}
